# Generated by Django 5.2.1 on 2025-06-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_manufacture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacture',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('article', models.CharField(max_length=20)),
                ('description', models.TextField(default='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.category')),
                ('manufacture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.manufacture')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
